# Build the Jaminator MSI.
# Reads the tool version from Program.cs (single source of truth) and feeds it to WiX.
#
# Pre-reqs:
#   - .NET SDK 8+
#   - WiX 4 global tool: dotnet tool install --global wix
#   - The EXE must already be built (dotnet build ... -c Release)

[CmdletBinding()]
param(
    [string]$Configuration = 'Release'
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
Push-Location $repoRoot
try {
    # Discover version from Program.cs
    $programCs = Get-Content -Raw "$repoRoot\src\Jaminator\Program.cs"
    if ($programCs -notmatch 'ToolVersion\s*=\s*"([\d.]+)"') {
        throw "Could not parse ToolVersion from Program.cs"
    }
    $version = $Matches[1]
    if (($version -split '\.').Count -lt 4) { $version = "$version.0" }  # MSI wants 4 parts
    Write-Host "Building Jaminator MSI v$version"

    # --- Resolve PAT ---
    $patFile = "$repoRoot\installer\secrets\wifi-pat.txt"
    $urlFile = "$repoRoot\installer\secrets\wifi-secrets-url.txt"

    if (Test-Path $patFile) {
        $wifiPat = (Get-Content -Raw $patFile).Trim()
    } elseif ($env:JAMINATOR_WIFI_PAT) {
        $wifiPat = $env:JAMINATOR_WIFI_PAT.Trim()
    } else {
        throw "installer/secrets/wifi-pat.txt not found AND `$env:JAMINATOR_WIFI_PAT not set — cannot embed Wi-Fi PAT. See installer/secrets/README.md for setup."
    }

    if (Test-Path $urlFile) {
        $secretsUrl = (Get-Content -Raw $urlFile).Trim()
    } elseif ($env:JAMINATOR_WIFI_SECRETS_URL) {
        $secretsUrl = $env:JAMINATOR_WIFI_SECRETS_URL.Trim()
    } else {
        throw "installer/secrets/wifi-secrets-url.txt not found AND `$env:JAMINATOR_WIFI_SECRETS_URL not set — cannot embed Wi-Fi secrets URL. See installer/secrets/README.md for setup."
    }

    # Build-time fail-closed: a file that exists but is blank/whitespace-only Trims
    # to "" and would silently embed an empty secret. Fail here with operator-facing
    # feedback instead of deferring to the launch-time guard in Program.Main.
    if ([string]::IsNullOrWhiteSpace($wifiPat)) {
        throw "Wi-Fi PAT resolved to an empty value — check installer/secrets/wifi-pat.txt (or `$env:JAMINATOR_WIFI_PAT). See installer/secrets/README.md."
    }
    if ([string]::IsNullOrWhiteSpace($secretsUrl)) {
        throw "Wi-Fi secrets URL resolved to an empty value — check installer/secrets/wifi-secrets-url.txt (or `$env:JAMINATOR_WIFI_SECRETS_URL). See installer/secrets/README.md."
    }

    # --- Generate BuildSecrets.g.cs ---
    $generatedDir = "$repoRoot\src\Jaminator\Generated"
    $generatedFile = "$generatedDir\BuildSecrets.g.cs"
    New-Item -ItemType Directory -Path $generatedDir -Force | Out-Null

    # Emit as C# verbatim string literals (@"...") so a backslash in a PAT or URL
    # passes through unchanged — a regular literal would interpret "\t", "\u", etc.
    # as escape sequences (silently wrong value, or a compiler error). Verbatim
    # strings only require doubling embedded double-quotes.
    $escapedPat = $wifiPat -replace '"', '""'
    $escapedUrl = $secretsUrl -replace '"', '""'

    $content = @"
// Auto-generated by installer/build.ps1 at build time. Do not edit; do not commit.
// Contents are gitignored. Rotation: replace installer/secrets/wifi-pat.txt and rebuild.
namespace Jaminator
{
    internal static class BuildSecrets
    {
        internal const string WifiPat = @"$escapedPat";
        internal const string SecretsUrl = @"$escapedUrl";
    }
}
"@
    Set-Content -Path $generatedFile -Value $content -NoNewline -Encoding UTF8
    Write-Host "Generated $generatedFile" -ForegroundColor Cyan

    # Ensure EXE is built
    $binDir = "$repoRoot\src\Jaminator\bin\$Configuration\net48"
    if (-not (Test-Path "$binDir\Jaminator.exe")) {
        Write-Host "Building solution..."
        dotnet build "$repoRoot\Jaminator.sln" -c $Configuration | Out-Host
    }

    # Build MSI
    $outDir = "$repoRoot\build"
    New-Item -ItemType Directory -Path $outDir -Force | Out-Null
    $msi = "$outDir\Jaminator.msi"
    if (Test-Path $msi) { Remove-Item $msi -Force }

    & wix build "$repoRoot\installer\installer.wxs" `
        -d "Version=$version" `
        -d "SourceDir=$binDir" `
        -bindpath "$repoRoot\installer" `
        -ext WixToolset.UI.wixext `
        -ext WixToolset.Util.wixext `
        -arch x64 `
        -o $msi
    if ($LASTEXITCODE -ne 0) { throw "wix build failed" }

    $size = [math]::Round((Get-Item $msi).Length / 1MB, 2)
    Write-Host "Built $msi ($size MB)" -ForegroundColor Green
}
finally {
    Pop-Location
}
